
export const SUCCESFULL_GET = 'SUCCESFULL_GET';

export const ERROR_GET = 'ERROR_GET';

export const SUCCESFUL_GET_EMPLEADO = 'SUCCESFULL_GET_EMPLEADO';

export const ERROR_GET_EMPLEADO = 'ERROR_GET_EMPLEADO';

export const SUCCESFUL_GET_ROLES = 'SUCCESFUL_GET_ROLES';

export const ERROR_GET_ROLES = 'ERROR_GET_ROLES';
